### ISSUE TITLE
Integrate WikiSpeedBot into the Django App

### ISSUE THREAD

**Issue by Mehdi-RZ** [Mehdi-RZ/WikiSpeedRun#1]
### Description
Integrate WikiSpeedBot into the Django App, so we can output results directly into the browser

### Files

[feature/wikispeedbot/WikiSpeedBot.py](https://github.com/Mehdi-RZ/WikiSpeedRun/blob/feature/wikispeedbot/WikiSpeedBot.py)

### Tasks

- [ ] integrate WikiSpeedBot into the django app
- [ ] display page : input forms , output results
- [ ] wikipedia iframe test
