### ISSUE TITLE
README and Wiki documentation

### ISSUE THREAD

**Issue by Mehdi-RZ** [Mehdi-RZ/WikiSpeedRun#2]
### Description
README and Wiki documentation , initialize a template for both wiki and README

### To-Do
- [ ] create a Template for README
- [ ] create a Template for Wiki
- [ ] init a documentation for README and Wiki
